use_frameworks!

target 'ZSCarouselView_Example' do
  pod 'ZSCarouselView', :path => '../'
  pod 'ZSViewUtil'
  pod 'Kingfisher'

  target 'ZSCarouselView_Tests' do
    inherit! :search_paths

    
  end
end
